export default function(){
	return [
		{ 	featured: true,
			number: 'I',
			title: 'Buber', 
			githubrepo: 'https://github.com/mstorino/buber', 
			summary: 'Track the availability of local, trusted babysitters in real time.', 
			technologiesUsed: 'MERN, Bootstrap, Javascript, Node.js, Express, MongoDB, Mongoose, Passport and React.js.', 
			image1: "assets/img/github3.png", 
			detail1: 'Enable caretakers to hire babysitter immediately or in the future. Unlike exisiting sites, Buber only displays sitters within your neighborhood.',
			detail2: 'Caretakers creat a family profile and see which sitters are available. Stters, create a profile and toggle on/off availability.',
			detail3: "RESTful routes for server and api calls, create react components for sitter lists and details, front-end design and logos",
		},
		{ 	featured: true,
			number: 'II',
			title: 'TutorKarma', 
			githubrepo: 'https://github.com/mstorino/tutorkarma', 
			summary: 'Community based tutoring application', 
			technologiesUsed: 'Git, Bootstrap, JavaScript, Node, npm, Express.js, MySQL, Schema and Seed files, Sequelize.js, RESTful Routes, External APIs, jQuery and Handlebars.', 
			image1: "url('../assets/css/portfolio3.jpg')",
			detail1: 'Data-focused application connecting students with tutors in their local community based on area of expertise. tutorKarma utilizes a data persistence layer (MySQL) with full CRUD capabiliites.',
			detail2: 'Students find and book tutors through a customized student portal that displays tutors based on subject matter or name.',
			detail3: 'Responsible for API routes, Handlebars, jQuery, design for tutor booking landing pages and logo'
		},
		{ 	featured: true,
			number: 'III',
			title: 'Concession Butler', 
			githubrepo: 'https://github.com/mstorino/concessionbutler', 
			summary: 'Web application to assist in taking food orders', 
			technologiesUsed: 'Bootstrap, jQuery, Pressure.js, Moment.js, Firebase', 
			image1: "url('../assets/css/portfolio3.jpg')", 
			detail1: 'Worked with team to develop fluid interactive application that expedites concession purchases',
			detail2: 'Orders are taken and the total is calculated. Then the order is submitted to the the cook for expediting.',
			detail3: 'Responsible for cohesive design, graceful mobile-first CSS and lightweight assets and logo',
		},
		{ 	featured: false,
			number: '',
			title: 'FriendFinder', 
			githubrepo: 'https://github.com/mstorino/friendFinder', 
			summary: 'Personality Quiz determining which character you are from Ready Player One', 
			technologiesUsed: 'MySQL, Node, Express, Handlebars, and a custom ORM', 
			image1: "url('../assets/css/portfolio3.jpg')", 
			detail1: '',
			detail2: '',
			detail3: '',
		},
		{ 	featured: false,
			number: '',
			title: 'Food52 Scraper', 
			githubrepo: 'https://github.com/mstorino/mongoScraping', 
			summary: 'App that scrapes recipes from Food52', 
			technologiesUsed: 'Bootstrap, Mongoose, Cheerio, MongoDB', 
			image1: "url('../assets/css/portfolio3.jpg')", 
			detail1: '',
			detail2: '',
			detail3: '',
		},
		{ 	featured: false,
			number: '',
			title: 'Flashcard Generator', 
			githubrepo: 'https://github.com/mstorino/FlashcardGenerator', 
			summary: 'backend basic flashcard application', 
			technologiesUsed: 'Bootstrap, Mongoose, Cheerio, MongoDB', 
			image1: "url('../assets/css/portfolio3.jpg')", 
			detail1: '',
			detail2: '',
			detail3: '',
		},
		{ 	featured: false,
			number: '',
			title: 'Cake', 
			githubrepo: 'https://github.com/mstorino/FlashcardGenerator', 
			summary: 'Dynamic log of items.', 
			technologiesUsed: 'MySQL, Node, Express, Handlebars, and a custom ORM', 
			image1: "url('../assets/css/portfolio3.jpg')", 
			detail1: '',
			detail2: '',
			detail3: '',
		},
		{ 	featured: false,
			number: '',
			title: 'Bamazon', 
			githubrepo: 'https://github.com/mstorino/bamazon', 
			summary: 'An Amazon-like storefront created with the MySql server. It takes in customer orders and depletes inventory.', 
			technologiesUsed: 'MySQL, Node, Express, Handlebars, and a custom ORM', 
			image1: "url('../assets/css/portfolio3.jpg')", 
			detail1: '',
			detail2: '',
			detail3: '',
		},
		{ 	featured: false,
			number: '',
			title: 'Liribot', 
			githubrepo: 'https://github.com/mstorino/liriBot', 
			summary: 'Command line node app that takes in parameters and gives you back data based in a Language Interpretation and Recognition Interface (LIRI).', 
			technologiesUsed: 'MySQL, Node, Express, Handlebars, and a custom ORM', 
			image1: "url('../assets/css/portfolio3.jpg')", 
			detail1: '',
			detail2: '',
			detail3: '',
		},
		{ 	featured: false,
			number: '',
			title: 'gifTastic', 
			githubrepo: 'https://github.com/mstorino/gifTastic', 
			summary: 'Dynamic webpage', 
			technologiesUsed: 'MySQL, Node, Express, Handlebars, and a custom ORM', 
			image1: "url('../assets/css/portfolio3.jpg')", 
			detail1: '',
			detail2: '',
			detail3: '',
		},
		{ 	featured: false,
			number: '',
			title: 'Trivia Game', 
			githubrepo: 'https://github.com/mstorino/TriviaGame', 
			summary: 'Dynamic webpage', 
			technologiesUsed: 'jQuery & Javascript', 
			image1: "url('../assets/css/portfolio3.jpg')", 
			detail1: '',
			detail2: '',
			detail3: '',
		},
	]
}