export default function(){
	return [
		{ 	featured: true,
			number: 'I',
			title: 'Buber', 
			githubrepo: 'https://github.com/mstorino/buber', 
			summary: 'Babysitting + Uber = Buber. Unlike exisiting babysitter services, Buber allows users to see what babysitters are immediately available so that users may book local, trusted babysitters in real time.', 
			technologiesUsed: 'MERN, Bootstrap, Javascript, Node.js, Express, MongoDB, Mongoose, Passport and React.js.', 
			image1: "/portfolio/assets/img/buber1.jpg", 
			image2: "/portfolio/assets/img/buber3.jpg", 
			image3: "/portfolio/assets/img/buber4.jpg", 
			image4: "/portfolio/assets/img/buber5.jpg", 
			image5: "/portfolio/assets/img/buber2.jpg", 
			detail1: 'The babysitters are refined to your neighborhood. Buber utilized passport to allow users to login and create a profile. Caretakers then book a sitter for immediate or future appointments. Babysitters toggle on/off their availability and confirm pending appointment requests.',
			detail2: "Built RESTful API and server routes, implemented React.js, designed front-end and logos.",
		},
		{ 	featured: true,
			number: 'II',
			title: 'TutorKarma', 
			githubrepo: 'https://github.com/mstorino/tutorkarma', 
			summary: 'Community based tutoring application utilizing a data persistence layer (MySQL) with full CRUD capabiliites.', 
			technologiesUsed: 'Git, Bootstrap, JavaScript, Node, npm, Express.js, MySQL, Schema and Seed files, Sequelize.js, RESTful Routes, External APIs, jQuery and Handlebars.', 
			image1: "/portfolio/assets/img/tk1.jpg", 
			image2: "/portfolio/assets/img/tk3.jpg", 
			image3: "/portfolio/assets/img/tk2.jpg", 
			image4: "/portfolio/assets/img/tk4.jpg", 
			image5: "/portfolio/assets/img/tk5.jpg", 
			detail1: 'tutorKarma connects students with local tutors filtered by area of expertise. Students find and book tutors through a customized student portal that displays tutors based on subject matter or name.',
			detail2: 'Built API routes, implemented Handlebars and jQuery functionality to sort tutors and subject matter, established landing page design and assets.'
		},
		{ 	featured: true,
			number: 'III',
			title: 'Concession Butler', 
			githubrepo: 'https://github.com/mstorino/concessionbutler', 
			summary: 'Web application for expediting concession stand food orders.', 
			technologiesUsed: 'Bootstrap, jQuery, Pressure.js, Moment.js, Firebase', 
			image1: "/portfolio/assets/img/cb1.jpg", 
			image2: "/portfolio/assets/img/cb2.jpg", 
			image3: "/portfolio/assets/img/cb3.jpg", 
			image4: "/portfolio/assets/img/cb4.jpg", 
			image5: "/portfolio/assets/img/cb5.jpg", 
			detail1: 'Concession Butler is a fluid interactive application that allows users to take orders, calculates the total due, calculates the change owed to the customer and sends the order to the concession stand for expediting.',
			detail2: 'Created cohesive design, graceful mobile-first CSS, lightweight assets and logo.',
		},
		{ 	featured: false,
			number: '',
			title: 'FriendFinder', 
			githubrepo: 'https://github.com/mstorino/friendFinder', 
			summary: 'Personality Quiz determining which character you are from Ready Player One', 
			technologiesUsed: 'MySQL, Node, Express, Handlebars, and a custom ORM', 
			image1: "url('../assets/css/portfolio3.jpg')", 
			detail1: '',
			detail2: '',
			detail3: '',
		},
		{ 	featured: false,
			number: '',
			title: 'Food52 Scraper', 
			githubrepo: 'https://github.com/mstorino/mongoScraping', 
			summary: 'App that scrapes recipes from Food52', 
			technologiesUsed: 'Bootstrap, Mongoose, Cheerio, MongoDB', 
			image1: "url('../assets/css/portfolio3.jpg')", 
			detail1: '',
			detail2: '',
			detail3: '',
		},
		{ 	featured: false,
			number: '',
			title: 'Flashcard Generator', 
			githubrepo: 'https://github.com/mstorino/FlashcardGenerator', 
			summary: 'backend basic flashcard application', 
			technologiesUsed: 'Bootstrap, Mongoose, Cheerio, MongoDB', 
			image1: "url('../assets/css/portfolio3.jpg')", 
			detail1: '',
			detail2: '',
			detail3: '',
		},
		{ 	featured: false,
			number: '',
			title: 'Cake', 
			githubrepo: 'https://github.com/mstorino/FlashcardGenerator', 
			summary: 'Dynamic log of items.', 
			technologiesUsed: 'MySQL, Node, Express, Handlebars, and a custom ORM', 
			image1: "url('../assets/css/portfolio3.jpg')", 
			detail1: '',
			detail2: '',
			detail3: '',
		},
		{ 	featured: false,
			number: '',
			title: 'Bamazon', 
			githubrepo: 'https://github.com/mstorino/bamazon', 
			summary: 'An Amazon-like storefront created with the MySql server. It takes in customer orders and depletes inventory.', 
			technologiesUsed: 'MySQL, Node, Express, Handlebars, and a custom ORM', 
			image1: "url('../assets/css/portfolio3.jpg')", 
			detail1: '',
			detail2: '',
			detail3: '',
		},
		{ 	featured: false,
			number: '',
			title: 'Liribot', 
			githubrepo: 'https://github.com/mstorino/liriBot', 
			summary: 'Command line node app that takes in parameters and gives you back data based in a Language Interpretation and Recognition Interface (LIRI).', 
			technologiesUsed: 'MySQL, Node, Express, Handlebars, and a custom ORM', 
			image1: "url('../assets/css/portfolio3.jpg')", 
			detail1: '',
			detail2: '',
			detail3: '',
		},
		{ 	featured: false,
			number: '',
			title: 'gifTastic', 
			githubrepo: 'https://github.com/mstorino/gifTastic', 
			summary: 'Dynamic webpage', 
			technologiesUsed: 'MySQL, Node, Express, Handlebars, and a custom ORM', 
			image1: "url('../assets/css/portfolio3.jpg')", 
			detail1: '',
			detail2: '',
			detail3: '',
		},
		{ 	featured: false,
			number: '',
			title: 'Trivia Game', 
			githubrepo: 'https://github.com/mstorino/TriviaGame', 
			summary: 'Dynamic webpage', 
			technologiesUsed: 'jQuery & Javascript', 
			image1: "url('../assets/css/portfolio3.jpg')", 
			detail1: '',
			detail2: '',
			detail3: '',
		},
	]
}